doctrine:
    dbal:
#        override_url: true
#        url: '%env(resolve:DATABASE_URL)%'

        default_connection: default
        connections:
            default:
                # This will be the connection used by the default entity manager
                url: '%env(resolve:DATABASE_URL)%'
#                driver: 'pdo_pgsql'
                server_version: 'mariadb-10.5.12'
                charset: UTF8
            migrations:
                # This will be the connection used for playing the migrations
                url: '%env(resolve:DATABASE_MIGRATIONS_URL)%'
#                driver: 'pdo_pgsql'
                server_version: 'mariadb-10.5.12'
                charset: UTF8

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
#    orm:
#        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Infrastructure/Entity'
#                prefix: 'App\Infrastructure\Entity'
#                alias: InfratructureEntity
